# Generated by Django 6.0.6 on 2026-07-22 02:45

import hub.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resources/%Y/%m/', validators=[hub.validators.validate_file_size, hub.validators.validate_file_extension]),
        ),
    ]
